//import React from 'react'

//const Api = () =>{
  //    fetch(
  //    "https://www.swiggy.com/dapi/restaurants/list/v5?lat=13.198909&lng=77.7068926&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING"
     // .then((res) => res.json())

      //.then((json) => {
     // const data = json?.data?.cards?.[4]?.card?.gridElements?.infoWithStyle?.restaurants
      //  setRestaurants(data);
      //console.log("rrrrrr",data);
     // })
     // .catch((err) =>console.log(err));

//}
//export default Api

let resList =[
  {
    id: 1,
    name: "Pizza Hut",
    cuisines: "Pizza, Burger, French-Fries, Rolls",
    rating: "3.7",
    offers: "₹250 for TWO",
    deliveryTime: "25 minutes",
    image:"https://b.zmtcdn.com/data/pictures/chains/4/3300794/fdf5e5079a0352d872204dad39bc0f08.jpg?fit=around|960:500&crop=960:500;*,*",
  },
  {
    id: 2,
    name: "Domino's Pizza",
    cuisines: "Pizza, Pasta, Sides",
    rating: "4.5",
    offers: "₹300 for TWO",
    deliveryTime: "30 minutes",
    image: "https://b.zmtcdn.com/data/pictures/chains/5/21394315/6e96bfb00b9dd20195385f866d3e0e10_featured_v2.jpg",
  },
  {
    id: 3,
    name: "Burger King",
    cuisines: "Burgers, Fries, Desserts",
    rating: "4.2",
    offers: "₹200 for TWO",
    deliveryTime: "20 minutes",
    image: "https://b.zmtcdn.com/data/pictures/chains/5/61555/c8008523810583087401ff292c1763a3.jpg?fit=around|750:500&crop=750:500;*,*",
  },
  {
    id: 4,
    name: "Subway",
    cuisines: "Sandwiches, Salads",
    rating: "4.4",
    offers: "₹250 for TWO",
    deliveryTime: "25 minutes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqFPyg6N-Z51ndufYvBvyN-oUe8tMc4IxOrw&s",
  },
  {
    id: 5,
    name: "KFC",
    cuisines: "Chicken, Burgers, Rice Bowls",
    rating: "2.0",
    offers: "₹350 for TWO",
    deliveryTime: "35 minutes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHI2iD2KRZ3pw9PvA4wnSDmfHMi0URvNMyvQ&s",
  },
  {
    id: 6,
    name: "McDonald's",
    cuisines: "Burgers, Wraps, Desserts",
    rating: "4.6",
    offers: "₹250 for TWO",
    deliveryTime: "20 minutes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsNPNW78CASQb2jEPHt3B_x2ztCrYtYBtFIw&s",
  },
  {
    id: 7,
    name: "Starbucks",
    cuisines: "Coffee, Snacks, Desserts",
    rating: "4.7",
    offers: "₹400 for TWO",
    deliveryTime: "15 minutes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp1pIYCahUibQbzkqShFG6567llionlFYuyA&s",
  },{id: 8,
    name: "Haldiram's",
    cuisines: "Indian Snacks, Sweets, Thali",
    rating: "4.0",
    offers: "₹300 for TWO",
    deliveryTime: "40 minutes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ03WBvCHl09MJDc-a6_4FUNUGW6Bjt710hfA&s",
  },
  {id: 9,
    name: "Dosa Plaza",
    cuisines: "South Indian, Dosa",
    rating: "4.3",
    offers: "₹200 for TWO",
    deliveryTime: "30 minutes",
    image: "https://lh3.googleusercontent.com/PtrGJ4ViYaZOVAE6TpU6dakkN6Mk-j_rsXBOwqXdmK1eY4Qd0upHel8OXABsaXhrzmI5d5j9QgxfEFSQ0RtklyQvgPM=w1200-rw",
  },
  {
    id: 10,
    name: "Taco Bell",
    cuisines: "Mexican, Tacos, Burritos",
    rating: "3.6",
    offers: "₹250 for TWO",
    deliveryTime: "25 minutes",
    image: "https://b.zmtcdn.com/data/pictures/2/18820472/24a2231f71c1ba0b8f57e53f54930ad3.jpg?fit=around|960:500&crop=960:500;*,*",
  },{
    id: 11,
    name: "Dunkin' Donuts",
    cuisines: "Donuts, Coffee, Wraps",
    rating: "2.5",
    offers: "₹250 for TWO",
    deliveryTime: "20 minutes",
    image: "https://b.zmtcdn.com/data/pictures/2/308772/6cc9f17a1724d6c55acdc8ec52acb133.jpg?fit=around|750:500&crop=750:500;*,*",
  },
  {
    id: 12,
    name: "Baskin Robbins",
    cuisines: "Ice Cream, Shakes",
    rating: "3.7",
    offers: "₹150 for TWO",
    deliveryTime: "15 minutes",
    image:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/a3/30/fc/omg-so-good.jpg?w=900&h=500&s=1",
  },
  {
    id:13,
    name: "Pind Balluchi",
    cuisines: "North Indian, Punjabi",
    rating: "4.1",
    offers: "₹500 for TWO",
    deliveryTime: "45 minutes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz7qeSmPR99LJhs-Z_3C3-7_T60PtJz2SCag&s",
  },
  {
    id: 14,
    name: "Wow! Momo",
    cuisines: "Momos, Thukpa",
    rating: "4.4",
    offers: "₹150 for TWO",
    deliveryTime: "20 minutes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrR5G5Tg4soRBSrSgM2GVgBIJ5gisms0avqQ&s",
  },
  {
    id: 15,
    name: "Chaayos",
    cuisines: "Tea, Snacks, Breakfast",
    rating: "4.3 ",
    offers: "₹200 for TWO",
    deliveryTime: "25 minutes",
    image: "https://b.zmtcdn.com/data/pictures/8/19248338/03b2f4b59b8e40d18ba5818b2d56feda.jpg",
  },
  {
    id: 16,
    name: "Behrouz Biryani",
    cuisines: "Biryani, Kebabs",
    rating: "3.8",
    offers: "₹400 for TWO",
    deliveryTime: "30 minutes",
    image: "https://www.madhuseverydayindian.com/wp-content/uploads/2022/11/easy-vegetable-biryani.jpg",
  },
  {
    id: 17,
    name: "Faasos",
    cuisines: "Wraps, Rolls, Bowls",
    rating: "4.2",
    offers: "₹250 for TWO",
    deliveryTime: "30 minutes",
    image: "https://tb-static.uber.com/prod/image-proc/processed_images/377edd0245fda6115c258a53e940ad6f/3ac2b39ad528f8c8c5dc77c59abb683d.jpeg",
  },
  {
    id: 18,
    name: "Box8",
    cuisines: "Indian Meals, Curries, Wraps",
    rating: "4.3",
    offers: "₹300 for TWO",
    deliveryTime: "25 minutes",
    image: "https://www.franchiseindia.com/uploads/content/ri/art/box8-high-on-expansion-to-enter--2cde9ced68.jpg",
  },
  {
    id: 19,
    name: "Paradise Biryani",
    cuisines: "Hyderabadi Biryani",
    rating: "4.4 stars",
    offers: "₹450 for TWO",
    deliveryTime: "35 minutes",
    image: "https://tse3.mm.bing.net/th/id/OIP.0dZ8CEY42paYl1eLC8hiYwHaFj?r=0&pid=ImgDet&w=184&h=138&c=7&dpr=1.3&o=7&rm=3",
  },{
    id: 20,
    name: "Barbeque Nation",
    cuisines: "Buffet, Grills, Indian",
    rating: "4.6",
    offers: "₹800 for TWO",
    deliveryTime: "35 minutes",
    image: "https://gumlet.assettype.com/freepressjournal/2021-03/446d84db-70b8-421b-a2f0-0c905002a951/barbeque_nation.jpg",
  },
]
export default resList;